/* @generated by TypeSQL. Do not edit by hand. */
/* Source: Queries.res */

module M1 = {
  %%raw("const getUserSql = `
  	
  	  /* @name GetUser */
  	  select id, name from users where id = ?
  	
  	`
  const getUserStatementCache = new WeakMap()
  function getGetUserStatement(db) {
    const cached = getUserStatementCache.get(db)
    if (cached != null) {
      return cached
    }
    const statement = db.prepare(getUserSql)
    getUserStatementCache.set(db, statement)
    return statement
  }
  function getUser(db, params) {
    const res = getGetUserStatement(db).raw(true)
      .get([params.id])
    return res ? mapArrayToGetUserResult(res) : null
  }
  function mapArrayToGetUserResult(data) {
    const result = {
      id: data[0],
      name: data[1],
    }
    return result
  }
  ")

  @@warning("-30")
  type rec getUserParams = {
    id: int
  }
  and getUserResult = {
    id: int,
    name: string
  }

  external getUser: (BetterSqlite3.client, getUserParams) => Null.t<getUserResult> = "getUser"
  let run: (BetterSqlite3.client, getUserParams) => Null.t<getUserResult> = (db, params) => {
    getUser(db, params)
  }

  let query = run
  let default = query
}

module M2 = {
  %%raw("const renameUserSql = `
  	
  	  /* @name RenameUser */
  	  update users set name = ? where id = ?
  	
  	`
  const renameUserStatementCache = new WeakMap()
  function getRenameUserStatement(db) {
    const cached = renameUserStatementCache.get(db)
    if (cached != null) {
      return cached
    }
    const statement = db.prepare(renameUserSql)
    renameUserStatementCache.set(db, statement)
    return statement
  }
  function renameUser(db, data, params) {
    return getRenameUserStatement(db).run([data.name, params.id])
  }
  ")

  @@warning("-30")
  type rec renameUserData = {
    name: string
  }
  and renameUserParams = {
    id: int
  }
  and renameUserResult = {
    changes: float
  }

  external renameUser: (BetterSqlite3.client, renameUserData, renameUserParams) => renameUserResult = "renameUser"
  let run: (BetterSqlite3.client, renameUserData, renameUserParams) => renameUserResult = (db, data, params) => {
    renameUser(db, data, params)
  }

  let query = run
  let default = query
}
