import fs from 'node:fs';
import path from 'node:path';
import { generateReScriptWithClient, type RescriptSchemaInfo } from '../rescript-cli/service';
import type { DatabaseClient } from '../types';
import type { RescriptEmbeddedQuery } from './types';

export async function buildEmbeddedRescriptFile(
	dbClient: DatabaseClient,
	schemaInfo: RescriptSchemaInfo,
	sourcePath: string,
	srcDir: string,
	queries: RescriptEmbeddedQuery[]
) {
	const modules: string[] = [];

	for (const query of queries) {
		const { rescript } = await generateReScriptWithClient(dbClient, schemaInfo, query.queryName, query.sql);
		modules.push(renderEmbeddedQueryModule(query.index, trimExtraBlankLines(rescript)));
	}

	return renderEmbeddedRescriptFile(resolveEmbeddedSourceDisplayPath(sourcePath, srcDir), modules);
}

export function resolveEmbeddedRescriptFilePath(sourcePath: string, srcDir: string, outDir: string) {
	const relativeDir = path.relative(srcDir, path.dirname(sourcePath));
	const sourceBaseName = path.basename(sourcePath, '.res');
	return path.join(outDir, relativeDir, `${sourceBaseName}__typesql.res`);
}

export function resolveEmbeddedSourceDisplayPath(sourcePath: string, srcDir: string) {
	const relativeSourcePath = path.relative(srcDir, sourcePath);
	if (relativeSourcePath.length === 0) {
		return path.basename(sourcePath);
	}
	return relativeSourcePath.split(path.sep).join('/');
}

export function writeTextFileIfChanged(filePath: string, contents: string): 'created' | 'updated' | 'unchanged' {
	const existed = fs.existsSync(filePath);
	if (existed) {
		const currentContents = fs.readFileSync(filePath, 'utf8');
		if (currentContents === contents) {
			return 'unchanged';
		}
	}

	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, contents);
	return existed ? 'updated' : 'created';
}

export function deleteFileIfExists(filePath: string) {
	if (!fs.existsSync(filePath)) {
		return false;
	}
	fs.rmSync(filePath, { force: true });
	return true;
}

function renderEmbeddedRescriptFile(sourceDisplayPath: string, modules: string[]) {
	const lines = [
		'/* @generated by TypeSQL. Do not edit by hand. */',
		`/* Source: ${sourceDisplayPath} */`,
		'',
		modules.join('\n\n'),
		''
	];

	return lines.join('\n');
}

function renderEmbeddedQueryModule(index: number, rescript: string) {
	const indentedBody = indentRescriptModuleBody(rescript);
	return [`module M${index} = {`, indentedBody, `}`].join('\n');
}

function indentRescriptModuleBody(rescript: string) {
	return rescript
		.split('\n')
		.map((line) => (line.length > 0 ? `  ${line}` : ''))
		.join('\n');
}

function trimExtraBlankLines(value: string) {
	const lines = value.split('\n');
	while (lines[0] === '') {
		lines.shift();
	}
	while (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}
